[system]
    show_sql = false
    debug = true
    log = "log.txt"

#[database]
#   name = "sqlite3"
#   path = "./sql/fate.db"

[database]
   name = "mysql"
   username = "root"
   password = "111111"
   addr = "localhost"
   port = "3306"
   schema = "fate"
   local = "Asia/Shanghai"
   param = "?"

[mongodb]
    url = "localhost"
    username = "root"
    password = "v2RgzSuIaBlx"