[system]
#    sql = true
    debug = true
    log = "log111.txt"

[database]
   name = "sqlite3"
   path = "./fate.db"



#[database]
#   name = "mysql"
#   username = "root"
#   password = "123456"
#   addr = "localhost"
#   port = "3306"
#   schema = "fate"
#   local = "Asia/Shanghai"
#   param = "?"


